export const AUTH_SERVICE = 'IAuthService';
export const AUTH_JWT_SERVICE = 'IAuthJWTService';
export const USER_SERVICE = 'UserServiceImp';
export const USER_REPOSITORY = 'UserRepositoryImp';
export const AUTHOR_SERVICE = 'AuthorServiceImp';
export const APP_INTERCEPTOR = 'AppInterceptor';
export const INTERNATIONALIZATION_SERVICE = 'INTERNATIONALIZATION_SERVICE';
export const LITERARY_WORK_SERVICE = 'LiteraryWorkServiceImpl';
export const VOLUME_SERVICE = 'VOLUME_SERVICE';
export const DATA_SOURCE = 'DATA_SOURCE';
export const LITERARY_WORK_REPOSITORY = 'LITERARY_WORK_REPOSITORY';
export const INTERNATIONALIZATION_REPOSITORY =
  'INTERNATIONALIZATION_REPOSITORY';
export const AUTHOR_REPOSITORY = 'AUTHOR_REPOSITORY';
export const VOLUME_REPOSITORY = 'VOLUME_REPOSITORY';
export const USER_VOLUME_SERVICE = 'USER_VOLUME_SERVICE';
export const USER_VOLUME_REPOSITORY = 'USER_VOLUME_REPOSITORY';
