export const AUTH_SERVICE = 'IAuthService';
export const AUTH_JWT_SERVICE = 'IAuthJWTService';
export const USER_SERVICE = 'UserServiceImp';
export const USER_REPOSITORY = 'UserRepositoryImp';
export const AUTHOR_SERVICE = 'AuthorServiceImp';
export const APP_INTERCEPTOR = 'AppInterceptor';
export const INTERNATIONALIZATION_SERVICE = 'INTERNATIONALIZATION_SERVICE';
export const I_LITERARY_WORK_SERVICE = 'ILiteraryWorkService';
export const I_VOLUME_SERVICE = 'IVolumeService';
export const DATA_SOURCE = 'DATA_SOURCE';
export const I_LITERARY_WORK_REPOSITORY = 'I_LITERARY_WORK_REPOSITORY';
export const I_INTERNATIONALIZATION_REPOSITORY =
  'I_INTERNATIONALIZATION_REPOSITORY';
export const AUTHOR_REPOSITORY = 'AUTHOR_REPOSITORY';
export const I_VOLUME_REPOSITORY = 'I_VOLUME_REPOSITORY';
export const I_USER_VOLUME_SERVICE = 'I_USER_VOLUME_SERVICE';
export const I_USER_VOLUME_REPOSITORY = 'I_USER_VOLUME_REPOSITORY';
